//package net.runningcode.dao;
//
//import android.database.sqlite.SQLiteDatabase;
//
//import java.util.Map;
//
//import de.greenrobot.dao.AbstractDao;
//import de.greenrobot.dao.AbstractDaoSession;
//import de.greenrobot.dao.identityscope.IdentityScopeType;
//import de.greenrobot.dao.internal.DaoConfig;
//
//import net.runningcode.bean.Express;
//
//import net.runningcode.dao.ExpressDao;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see de.greenrobot.dao.AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig expressDaoConfig;
//
//    private final ExpressDao expressDao;
//
//    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        expressDaoConfig = daoConfigMap.get(ExpressDao.class).clone();
//        expressDaoConfig.initIdentityScope(type);
//
//        expressDao = new ExpressDao(expressDaoConfig, this);
//
//        registerDao(Express.class, expressDao);
//    }
//
//    public void clear() {
//        expressDaoConfig.getIdentityScope().clear();
//    }
//
//    public ExpressDao getExpressDao() {
//        return expressDao;
//    }
//
//}
