package net.runningcode.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EXP_NO".
 */
public class Express {

    private Long id;
    /** Not-null value. */
    private String expNo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Express() {
    }

    public Express(Long id) {
        this.id = id;
    }

    public Express(Long id, String expNo) {
        this.id = id;
        this.expNo = expNo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getExpNo() {
        return expNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setExpNo(String expNo) {
        this.expNo = expNo;
    }

    // KEEP METHODS - put your custom methods here
    public Express(String expNo) {
        this.expNo = expNo;
    }
    // KEEP METHODS END

}
