package net.runningcode.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Entity mapped to table "EXP_NO".
 */
public class Express extends RealmObject {
    @PrimaryKey
    private String expNo;

    public Express() {
    }

    public Express(String expNo) {
        this.expNo = expNo;
    }

    /** Not-null value. */
    public String getExpNo() {
        return expNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setExpNo(String expNo) {
        this.expNo = expNo;
    }

}
